# Copyright 2023-2026 Udo Schmitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# file: tools/generate_webui_help_excerpts.jl
# purpose: generate app/src/webui/help_excerpts.jl, the documentation
#          sections the Web UI help pages (/help/<topic>) show, the two
#          help pages (/help, /help/reference) and the search index, from the
#          `doc` targets of the help registry (WEBUI_HELP_TOPICS in
#          app/src/webui/docs.jl). The Web UI reads nothing from docs/src at
#          run time (0.18.0 hard cut): the sections are extracted HERE, at
#          authoring time, and shipped as Julia source, so the help works
#          without the published site and for the version that is running.
#          Two products: the Web UI manual (docs/src/webui.md in full, the
#          page that explains the Web UI itself, shown at /help) and one
#          section per help topic: from the heading that carries the
#          `(@id anchor)` label to the next heading of the same or a higher
#          level. A section of the Web UI page ships whole, a section of a
#          library page ships its lead paragraph only (the library
#          documentation is not duplicated in the application, the help
#          page links to it). `!!! details` reasoning blocks stay online,
#          Documenter references become plain text, relative page links
#          become online links.
#          Usage: julia --project=app tools/generate_webui_help_excerpts.jl
#                 julia --project=app tools/generate_webui_help_excerpts.jl --check
#          --check regenerates in memory and fails when the committed file
#          differs (part of the docs gate).

using SparlectraApp

const _EXCERPT_OUTPUT = normpath(joinpath(dirname(pathof(SparlectraApp)), "webui", "help_excerpts.jl"))
const _EXCERPT_DOCS_SRC = normpath(joinpath(dirname(pathof(SparlectraApp)), "..", "..", "docs", "src"))
const _EXCERPT_HEADER = """
# Copyright 2023-2026 Udo Schmitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# file: app/src/webui/help_excerpts.jl
# purpose: GENERATED by tools/generate_webui_help_excerpts.jl from docs/src,
#          do not edit: the documentation sections the Web UI help pages
#          show, keyed by the registry's doc target (page/#anchor), and the
#          Web UI manual (docs/src/webui.md). Edit the documentation page
#          and regenerate.

"""

# The documentation pages that ARE the Web UI help: their sections ship
# whole and each page as a whole is an in-app page, the user help at /help
# and the reference at /help/reference.
const WEBUI_MANUAL_PAGE = "webui"
const WEBUI_REFERENCE_PAGE = "webui_reference"
const WEBUI_HELP_PAGE_ROUTES = Dict(WEBUI_MANUAL_PAGE => "/help", WEBUI_REFERENCE_PAGE => "/help/reference")

# The labels (`(@id label)`) of the headings of the help pages, label to
# page, so that a reference to one of them stays inside the Web UI. Filled
# by generate_webui_help_excerpts before anything is extracted.
const _EXCERPT_HELP_LABELS = Dict{String,String}()

function _excerpt_collect_help_labels!(docs_src::AbstractString)
  empty!(_EXCERPT_HELP_LABELS)
  for page in (WEBUI_MANUAL_PAGE, WEBUI_REFERENCE_PAGE)
    path = joinpath(docs_src, page * ".md")
    isfile(path) || continue
    for m in eachmatch(r"^#{1,6} \[[^\]]*\]\(@id ([A-Za-z0-9_.-]+)\)"m, read(path, String))
      _EXCERPT_HELP_LABELS[String(m.captures[1])] = page
    end
  end
  return _EXCERPT_HELP_LABELS
end

# The id a heading has on an in-app page: its label, else the text as a
# lowercase slug (a link written for the published site carries the slug
# with capitals).
_excerpt_fragment(fragment::AbstractString)::String = haskey(_EXCERPT_HELP_LABELS, fragment) ? String(fragment) : lowercase(String(fragment))

const _EXCERPT_HELP_REF = r"\[([^\]]+)\]\(@ref ([A-Za-z0-9_.-]+)\)"
const _EXCERPT_HELP_PAGE_LINK = r"\]\((webui_reference|webui)\.md(#[A-Za-z0-9_.-]+)?\)"

function _excerpt_help_ref(hit::AbstractString)::String
  m = match(_EXCERPT_HELP_REF, hit)
  page = get(_EXCERPT_HELP_LABELS, String(m.captures[2]), nothing)
  page === nothing && return String(hit)
  return string("[", m.captures[1], "](", WEBUI_HELP_PAGE_ROUTES[page], "#", m.captures[2], ")")
end

function _excerpt_help_page_link(hit::AbstractString)::String
  m = match(_EXCERPT_HELP_PAGE_LINK, hit)
  fragment = m.captures[2] === nothing ? "" : "#" * _excerpt_fragment(SubString(m.captures[2], 2))
  return string("](", WEBUI_HELP_PAGE_ROUTES[String(m.captures[1])], fragment, ")")
end

# Documenter syntax the Markdown standard library does not know:
# `[text](@ref)` and `[text](@ref name)` keep their text, `[text](@id name)`
# in a heading keeps the text. Relative page links become links into the
# published documentation; `SPARLECTRADOCS/` is replaced by the configured base URL
# when the help page renders.
function _excerpt_rewrite_links(text::AbstractString, page::AbstractString; same_page_online::Bool = true)::String
  # a reference to a labelled heading of a help page and a link to a help
  # page stay inside the Web UI (/help, /help/reference)
  out = replace(String(text), _EXCERPT_HELP_REF => _excerpt_help_ref)
  out = replace(out, _EXCERPT_HELP_PAGE_LINK => _excerpt_help_page_link)
  out = replace(out, r"\[([^\]]+)\]\(@ref\)" => s"\1")
  out = replace(out, r"\[([^\]]+)\]\(@ref [^)]*\)" => s"\1")
  out = replace(out, r"\]\(([A-Za-z0-9_]+)\.md(#[A-Za-z0-9_.-]+)?\)" => s"](SPARLECTRADOCS/\1/\2)")
  # a fragment of the same page: online from an excerpt, in-page in the manual
  same_page_online && (out = replace(out, r"\]\((#[A-Za-z0-9_.-]+)\)" => SubstitutionString("](SPARLECTRADOCS/$(page)/\\1)")))
  return out
end

# Heading text without its Documenter label, and the label itself ("" when
# the heading carries none).
function _excerpt_heading_parts(heading::AbstractString)
  m = match(r"^\[([^\]]*)\]\(@id ([A-Za-z0-9_.-]+)\)\s*$", strip(heading))
  m === nothing && return (String(strip(heading)), "")
  return (String(m.captures[1]), String(m.captures[2]))
end

"""
    extract_webui_help_manual(markdown) -> (markdown, anchors)

The whole page as the in-app manual: Documenter syntax converted, headings
stripped of their labels with the label recorded in `anchors` (heading text
to slug) so the renderer can give the heading the same id the published
site uses and in-page links keep working.
"""
function extract_webui_help_manual(markdown::AbstractString; page::AbstractString = WEBUI_MANUAL_PAGE)
  anchors = Pair{String,String}[]
  lines = String[]
  in_code = false
  for line in split(String(markdown), '\n')
    startswith(line, "```") && (in_code = !in_code)
    m = in_code ? nothing : match(r"^(#{1,6}) (.*)$", line)
    if m === nothing
      push!(lines, String(line))
      continue
    end
    text, label = _excerpt_heading_parts(m.captures[2])
    isempty(label) || push!(anchors, text => label)
    push!(lines, string(m.captures[1], " ", text))
  end
  return (markdown = _excerpt_rewrite_links(join(lines, '\n'), page; same_page_online = false), anchors = anchors)
end

# What a topic page shows of its section. A section of the Web UI manual
# page is Web UI guidance and ships whole. A section of a library page is
# library documentation, which the application does not duplicate: the
# topic page shows the lead paragraph (the first block) and links to the
# section online. Blocks are never cut in the middle.

# A line that opens a table, a fenced code block, an admonition, a list or
# a heading: not prose.
_excerpt_is_structural(line::AbstractString)::Bool = occursin(r"^(\||```|!!! |[-*] |\d+\. |#)", line)

# The first block is a lead paragraph only when it is prose.
_excerpt_is_prose(block::AbstractString)::Bool = !_excerpt_is_structural(first(split(block, '\n')))

# Markdown blocks: runs of lines separated by blank lines, a fenced code
# block counted as one block whatever it contains, and a table, fence or
# admonition that follows prose without a blank line starts a block of
# its own (so the lead paragraph never drags the table along).
function _excerpt_blocks(lines::AbstractVector{<:AbstractString})::Vector{String}
  blocks = String[]
  current = String[]
  in_code = false
  for line in lines
    if !in_code && !isempty(current) && _excerpt_is_prose(current[1]) && occursin(r"^(\||```|!!! )", line)
      push!(blocks, join(current, '\n'))
      empty!(current)
    end
    startswith(line, "```") && (in_code = !in_code)
    if !in_code && isempty(strip(line))
      isempty(current) || push!(blocks, join(current, '\n'))
      empty!(current)
    else
      push!(current, String(line))
    end
  end
  isempty(current) || push!(blocks, join(current, '\n'))
  return blocks
end

"""
    extract_webui_help_section(markdown, anchor, page) -> (title, markdown, truncated) or nothing

The section under the heading labelled `(@id anchor)`: up to the next heading
of the same or a higher level, without `!!! details` blocks, fenced code
respected (a `#` inside a code block is not a heading). A section of the
manual page ships whole; any other section is cut to its lead paragraph,
or to nothing when it opens with a table or a list (`truncated` says so).
"""
function extract_webui_help_section(markdown::AbstractString, anchor::AbstractString, page::AbstractString)
  lines = split(String(markdown), '\n')
  start = findfirst(l -> startswith(l, '#') && occursin("(@id $(anchor))", l), lines)
  start === nothing && return nothing
  level = length(match(r"^#+", lines[start]).match)
  title = strip(replace(lines[start][(level + 1):end], r"\[([^\]]*)\]\(@id [^)]*\)" => s"\1"))
  body = String[]
  in_code = false
  in_details = false
  for line in Iterators.drop(lines, start)
    startswith(line, "```") && (in_code = !in_code)
    if !in_code && occursin(r"^#{1,6} ", line) && length(match(r"^#+", line).match) <= level
      break
    end
    if !in_code && startswith(line, "!!! details")
      in_details = true
      continue
    end
    if in_details
      # an admonition body is indented by four spaces; the first unindented
      # non-empty line ends it
      (isempty(strip(line)) || startswith(line, "    ")) && continue
      in_details = false
    end
    push!(body, String(line))
  end
  blocks = _excerpt_blocks(body)
  # a library section: its lead paragraph when it has one, nothing when it
  # opens with a table or a list (the hint and the link carry the page then)
  kept = haskey(WEBUI_HELP_PAGE_ROUTES, page) ? blocks : (!isempty(blocks) && _excerpt_is_prose(blocks[1]) ? blocks[1:1] : String[])
  return (title = String(title), markdown = _excerpt_rewrite_links(join(kept, "\n\n"), page), truncated = length(kept) < length(blocks))
end

"""
    generate_webui_help_excerpts(; docs_src) -> (source, failures)

The Julia source of `help_excerpts.jl` and the list of targets without a
section. Targets are the unique `doc` values of the help registry, sorted.
"""
function generate_webui_help_excerpts(; docs_src::AbstractString = _EXCERPT_DOCS_SRC)
  failures = String[]
  _excerpt_collect_help_labels!(docs_src)
  targets = sort!(unique!([String(meta.doc) for meta in values(SparlectraApp.WEBUI_HELP_TOPICS) if !isempty(meta.doc)]))
  excerpts = Dict{String,String}()
  io = IOBuffer()
  print(io, _EXCERPT_HEADER)
  println(io, "const WEBUI_HELP_EXCERPTS = Dict{String,NamedTuple{(:title, :markdown, :truncated),Tuple{String,String,Bool}}}(")
  for target in targets
    m = match(r"^([A-Za-z0-9_]+)/#([A-Za-z0-9_.-]+)$", target)
    if m === nothing
      push!(failures, "$(target): not of the form page/#anchor")
      continue
    end
    page, anchor = String(m.captures[1]), String(m.captures[2])
    path = joinpath(docs_src, page * ".md")
    if !isfile(path)
      push!(failures, "$(target): $(page).md does not exist")
      continue
    end
    section = extract_webui_help_section(read(path, String), anchor, page)
    if section === nothing
      push!(failures, "$(target): no heading with (@id $(anchor)) in $(page).md")
      continue
    end
    excerpts[target] = section.markdown
    println(io, "  ", repr(target), " => (title = ", repr(section.title), ", markdown = ", repr(section.markdown), ", truncated = ", section.truncated, "),")
  end
  println(io, ")")
  index = NamedTuple{(:title, :url, :kind, :text),Tuple{String,String,String,String}}[]
  for (page, constant, what, kind) in ((WEBUI_MANUAL_PAGE, "WEBUI_HELP_MANUAL", "user help", "help"), (WEBUI_REFERENCE_PAGE, "WEBUI_HELP_REFERENCE", "reference", "reference"))
    path = joinpath(docs_src, page * ".md")
    if !isfile(path)
      push!(failures, "$(page).md (the Web UI $(what)) does not exist")
      continue
    end
    manual = extract_webui_help_manual(read(path, String); page = page)
    println(io)
    println(io, "# The Web UI ", what, " (docs/src/", page, ".md) and the ids of its labelled headings.")
    println(io, "const ", constant, " = ", repr(manual.markdown))
    println(io, "const ", constant, "_ANCHORS = Dict{String,String}(")
    for (text, label) in manual.anchors
      println(io, "  ", repr(text), " => ", repr(label), ",")
    end
    println(io, ")")
    append!(index, _excerpt_index_sections(manual.markdown, Dict{String,String}(manual.anchors), WEBUI_HELP_PAGE_ROUTES[page], kind))
  end
  # the help topics of the controls: label and hint, and the section the
  # topic page shows
  for topic in sort!(collect(keys(SparlectraApp.WEBUI_HELP_TOPICS)))
    meta = SparlectraApp.WEBUI_HELP_TOPICS[topic]
    isempty(String(meta.doc)) && continue
    text = strip(string(meta.hint, " ", SparlectraApp._webui_help_plain_text(get(excerpts, String(meta.doc), ""))))
    push!(index, (title = String(meta.label), url = "/help/" * String(topic), kind = "control", text = String(text)))
  end
  println(io)
  println(io, "# The search index of the help: one entry per section of the two help")
  println(io, "# pages and per help topic of a control, the text without markup.")
  println(io, "const WEBUI_HELP_SEARCH_INDEX = NamedTuple{(:title, :url, :kind, :text),Tuple{String,String,String,String}}[")
  for entry in index
    println(io, "  (title = ", repr(entry.title), ", url = ", repr(entry.url), ", kind = ", repr(entry.kind), ", text = ", repr(entry.text), "),")
  end
  println(io, "]")
  return (source = String(take!(io)), failures = failures)
end

# The sections of a help page for the search index: one entry per heading
# of level 2 to 4, the text up to the next heading, tables included.
function _excerpt_index_sections(markdown::AbstractString, anchors::AbstractDict, route::AbstractString, kind::AbstractString)
  entries = NamedTuple{(:title, :url, :kind, :text),Tuple{String,String,String,String}}[]
  title = ""
  body = String[]
  in_code = false
  flush! = () -> begin
    isempty(title) || push!(entries, (title = title, url = string(route, "#", SparlectraApp._webui_heading_id(title, anchors)), kind = String(kind), text = SparlectraApp._webui_help_plain_text(join(body, '\n'))))
    empty!(body)
  end
  for line in split(String(markdown), '\n')
    startswith(line, "```") && (in_code = !in_code)
    m = in_code ? nothing : match(r"^(#{2,4}) (.*)$", line)
    if m === nothing
      push!(body, String(line))
    else
      flush!()
      title = String(strip(m.captures[2]))
    end
  end
  flush!()
  return entries
end

"""
    check_webui_help_excerpts(; docs_src, io) -> Vector{String}

Failures: a target without a section, or a committed `help_excerpts.jl` that
differs from what the documentation sources generate now.
"""
function check_webui_help_excerpts(; docs_src::AbstractString = _EXCERPT_DOCS_SRC, io::IO = stdout)
  generated = generate_webui_help_excerpts(; docs_src)
  failures = copy(generated.failures)
  if !isfile(_EXCERPT_OUTPUT)
    push!(failures, "$(_EXCERPT_OUTPUT) is missing; run tools/generate_webui_help_excerpts.jl")
  elseif read(_EXCERPT_OUTPUT, String) != generated.source
    push!(failures, "$(basename(_EXCERPT_OUTPUT)) is out of date; run tools/generate_webui_help_excerpts.jl and commit the result")
  end
  println(io, "Web UI help excerpts: ", length(failures), " failure(s)")
  for f in failures
    println(io, "  FAIL ", f)
  end
  return failures
end

function main(args::Vector{String})
  if "--check" in args
    return isempty(check_webui_help_excerpts()) ? 0 : 1
  end
  generated = generate_webui_help_excerpts()
  for f in generated.failures
    println("  FAIL ", f)
  end
  isempty(generated.failures) || return 1
  write(_EXCERPT_OUTPUT, generated.source)
  println("wrote ", _EXCERPT_OUTPUT, " (", length(generated.source), " bytes)")
  return 0
end

if abspath(PROGRAM_FILE) == @__FILE__
  exit(Base.invokelatest(main, ARGS))
end
