# Copyright 2023–2026 Udo Schmitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# further details see: https://github.com/Welthulk/CIMDraw/blob/master/js/matpower.js

# Author: Udo Schmitz (https://github.com/Welthulk)
# Date: 20.6.2023
# file: src/exportMatPower.jl 

const comment = "% This file was generated by Sparlectra\n"

function writeHeader(sb_mva::Float64, file, case::AbstractString; has_transformer_loss_metadata::Bool = false)
  write(file, comment)
  write(file, "function mpc = $case\n")
  write(file, "%% MATPOWER Case Format : Version 2\n")
  if has_transformer_loss_metadata
    write(file, "%% SPARLECTRA EXTENSION WARNING\n")
    write(file, "%% This case contains Sparlectra-specific transformer active-loss metadata.\n")
    write(file, "%% Standard MATPOWER does not model this extension in its normal branch format.\n")
    write(file, "%% If this file is run directly in MATPOWER, transformer active losses may be missing\n")
    write(file, "%% or approximated differently, and power-flow results may deviate from Sparlectra.\n")
  end
  write(file, "mpc.version = '2';\n")
  write(file, "%%-----  Power Flow Data  -----%%\n")
  write(file, "%% system MVA base\n")
  write(file, "mpc.baseMVA = $sb_mva;\n")
end # writeHeader

function _sparlectra_transformer_loss_rows(net::Net)
  rows = NamedTuple[]
  bus_name_by_idx = Dict(n.busIdx => n.comp.cName for n in net.nodeVec)
  for (i, br) in enumerate(net.branchVec)
    meta = get(net.matpower_branch_metadata, i, nothing)
    kind = _matpower_branch_kind(net, i, br)
    g_pu = meta !== nothing && hasproperty(meta, :g_pu) ? Float64(meta.g_pu) : Float64(br.g_pu)
    (kind == "T" && g_pu != 0.0) || continue
    b_raw = meta !== nothing && hasproperty(meta, :b_s) ? Float64(meta.b_s) : NaN
    r_raw = meta !== nothing && hasproperty(meta, :r_ohm) ? Float64(meta.r_ohm) : NaN
    x_raw = meta !== nothing && hasproperty(meta, :x_ohm) ? Float64(meta.x_ohm) : NaN
    label = meta !== nothing && hasproperty(meta, :source_label) ? String(meta.source_label) :
      (meta !== nothing && hasproperty(meta, :orig_name) && meta.orig_name !== nothing ? String(meta.orig_name) : br.comp.cName)
    push!(rows, (
      branch_row = i,
      source_format = meta !== nothing && hasproperty(meta, :dtf_kind) ? "DTF" : "Sparlectra",
      original_id = label,
      from_bus_name = get(bus_name_by_idx, br.fromBus, string(br.fromBus)),
      to_bus_name = get(bus_name_by_idx, br.toBus, string(br.toBus)),
      r_raw = r_raw,
      x_raw = x_raw,
      g_raw = meta !== nothing && hasproperty(meta, :g_s) ? Float64(meta.g_s) : NaN,
      b_raw = b_raw,
      raw_units = meta !== nothing && hasproperty(meta, :g_s) ? "ohm_siemens" : "per_unit",
      r_pu = Float64(br.r_pu),
      x_pu = Float64(br.x_pu),
      g_pu = g_pu,
      b_pu = Float64(br.b_pu),
      active_no_load_g_pu = g_pu,
      reactive_shunt_b_pu = Float64(br.b_pu),
      allocation = "split_equally_to_terminal_bus_shunts",
      tap_ratio = Float64(br.ratio),
      phase_shift_deg = Float64(br.angle),
      stage_position = meta !== nothing && hasproperty(meta, :actual_tap_step) && meta.actual_tap_step !== nothing ? Float64(meta.actual_tap_step) : NaN,
    ))
  end
  return rows
end

function _matpower_bus_shunts(net::Net)
  gs = Dict(n.busIdx => 0.0 for n in net.nodeVec)
  bs = Dict(n.busIdx => 0.0 for n in net.nodeVec)
  for sh in net.shuntVec
    sh.status == 1 || continue
    gs[sh.busIdx] = get(gs, sh.busIdx, 0.0) + real(sh.y_pu_shunt) * net.baseMVA
    bs[sh.busIdx] = get(bs, sh.busIdx, 0.0) + imag(sh.y_pu_shunt) * net.baseMVA
  end
  return gs, bs
end

function writeBusData(net::Net, file)
  NodeVec = net.nodeVec
  shunt_gs, shunt_bs = _matpower_bus_shunts(net)
  write(file, "%% bus data\n")
  write(file, "mpc.bus = [\n")
  write(file, "%bus\ttype\tPd\tQd\tGs\tBs\tarea\tVm\tVa\tbaseKV\tzone\tVmax\tVmin\n")

  rows = 0
  hasPVBus = false
  slackIdx = 0
  vgSlack = 1.0
  for node in NodeVec
    rows += 1
    bus_i = node.busIdx
    Name = node.comp.cName
    ID = node.comp.cID

    val = Int(node._nodeType)
    if val <= 0 || val > 4
      @warn "Node $(ID) Node-Type $(val) not supported yet! -> set to 1 (PQ)"
      num = 1
    elseif val == 1
      num = 1
    elseif val == 2
      num = 2
      hasPVBus = true
    elseif val == 3
      num = 3
      Name = Name * " (slack)"
      slackIdx = bus_i
      vgSlack = node._vm_pu
    elseif val == 4
      num = 4
      Name = Name * " (isolated)"
    end

    pSum = (node._pƩLoad === nothing) ? 0.0 : node._pƩLoad
    qSum = (node._qƩLoad === nothing) ? 0.0 : node._qƩLoad

    GS = get(shunt_gs, node.busIdx, 0.0)
    BS = get(shunt_bs, node.busIdx, 0.0)

    area = (node._area === nothing) ? 1 : node._area #https://zepben.github.io/evolve/docs/cim/cim100/TC57CIM/IEC61970/Base/ControlArea/ControlArea/      

    vm_pu = (node._vm_pu === nothing) ? 1.0 : node._vm_pu
    va_deg = (node._va_deg === nothing) ? 0.0 : node._va_deg
    if isnothing(node.comp.cVN)
      @warn "Base Voltage not defined for node $(node.comp.cID) -> set to 1.0"
      baseKV = 1.0
    else
      baseKV = node.comp.cVN
    end

    lZone = (node._lZone === nothing) ? 1 : node._lZone

    Vmax = 1.1
    Vmin = 0.9
    #! format: off
    line = string(bus_i, "\t", num, "\t", pSum, "\t", qSum, "\t", GS, "\t", BS, "\t", area, "\t", vm_pu, "\t", va_deg, "\t", baseKV, "\t", lZone, "\t", Vmax, "\t", Vmin, "; %Bus: " * Name * " (ID: " * ID * ")\n")
    #! format: on
    write(file, line)
  end
  write(file, "];\n")
  return hasPVBus, slackIdx, vgSlack
end # writeBusData

function writeGeneratorData(sb_mva::Float64, NodeDict::Dict{Int,Node}, ProSumVec::Vector{ProSumer}, file, hasPVBus::Bool, slackIdx::Int, vgSlack::Float64)
  #! format: off
  write(file, "%% generator data\n")
  write(file, "mpc.gen = [\n")
  write(file, "%bus\tPg\tQg\tQmax\tQmin\tVg\tmBase\tstatus\tPmax\tPmin\tPc1\tPc2\tQc1min\tQc1max\tQc2min\tQc2max\tramp_agc\tramp_10\tramp_30\tramp_q\tapf\n")
  #! format: on
  slackGeneratorFound = false

  function getLine(node::Node, prosum::ProSumer)
    name = prosum.comp.cName
    cTypStr = string(prosum.comp.cTyp)
    pc1 = pc2 = qc1min = qc1max = qc2min = qc2max = ramp_agc = ramp_10 = ramp_30 = ramp_q = apf = 0.0

    bus_i = node.busIdx

    Vg = (node._vm_pu === nothing) ? 1.0 : node._vm_pu

    p = (prosum.pVal === nothing) ? 0 : prosum.pVal
    q = (prosum.qVal === nothing) ? 0 : prosum.qVal

    qmax = (prosum.maxQ === nothing) ? sb_mva : prosum.maxQ
    qmin = (prosum.minQ === nothing) ? -1.0 * sb_mva : prosum.minQ
    mbase = (prosum.ratedS === nothing) ? sb_mva : prosum.ratedS
    status = 1
    pmax = (prosum.maxP === nothing) ? sb_mva : prosum.maxP
    pmin = (prosum.minP === nothing) ? -1.0 * sb_mva : prosum.minP
    #! format: off
    line = string( bus_i, "\t", p, "\t", q, "\t", qmax,"\t", qmin, "\t", Vg, "\t",  mbase, "\t", status, "\t",  pmax, "\t", pmin, "\t",  pc1, "\t", pc2, 
                          "\t", qc1min, "\t", qc1max, "\t", qc2min, "\t", qc2max,  "\t",   ramp_agc, "\t", ramp_10,"\t",  ramp_30, "\t",  ramp_q, "\t",  apf, "; %Gen: ",  cTypStr, "_",  name, ")\n", )
    #! format: on
    return true, line
  end

  function getLineSlackGenerator()
    p = q = 0.0
    qmax = sb_mva
    qmin = -1.0 * sb_mva
    mbase = sb_mva
    status = 1
    pmax = sb_mva
    pmin = -1.0 * sb_mva
    pc1 = pc2 = qc1min = qc1max = qc2min = qc2max = ramp_agc = ramp_10 = ramp_30 = ramp_q = apf = 0.0
    #! format: off
    line = string(slackIdx, "\t",  p,"\t", q,"\t", qmax,"\t", qmin,"\t", vgSlack,"\t", mbase,"\t", status, "\t", pmax, "\t",  pmin, "\t", pc1, "\t", pc2, "\t", qc1min, "\t", qc1max, "\t",  qc2min, "\t", qc2max, 
                            "\t", ramp_agc,"\t",  ramp_10, "\t", ramp_30, "\t", ramp_q, "\t", apf,"; %Gen: Slack-Generator (ID: ", slackIdx, ")\n", )
    #! format: on
    return line
  end

  for prosum in ProSumVec
    if isGenerator(prosum.proSumptionType)
      bus_i = prosum.comp.cFrom_bus

      if haskey(NodeDict, bus_i)
        node = NodeDict[bus_i]
      else
        @warn "Node $(bus_i) not found"
        continue
      end

      if node.busIdx == 0
        @warn "Node $nodeID has no kidx: $(node.busIdx), $(node)"
        continue
      end

      if bus_i == slackIdx
        slackGeneratorFound = true
      end
      result, line = getLine(node, prosum)
      if result
        write(file, line)
      end
    end # if   
  end # for
  if !hasPVBus && !slackGeneratorFound
    @info "No PV-Bus found and no Slack-Generator defined -> add a Slack-Generator"
    line = getLineSlackGenerator()
    write(file, line)
  end # if
  write(file, "];\n")
end # WriteGeneratorData

function _matpower_branch_kind(net::Net, i::Int, br::Branch)
  meta = get(net.matpower_branch_metadata, i, nothing)
  if meta !== nothing && hasproperty(meta, :dtf_kind)
    return uppercase(string(meta.dtf_kind)) == "T" ? "T" : "L"
  elseif meta !== nothing && hasproperty(meta, :orig_kind)
    k = uppercase(String(meta.orig_kind))
    return k in ("T", "TRAFO", "TRANSFORMER") ? "T" : "L"
  end
  return (br.ratio != 1.0 || br.angle != 0.0) ? "T" : "L"
end

function writeBranchData(net::Net, file)
  branchVec = net.branchVec
  #! format: off
  write(file, "%% branch data\n")
  write(file, "mpc.branch = [\n")
  write(file, "%fbus\ttbus\tr\tx\tb\trateA\trateB\trateC\tratio\tangle\tstatus\tangmin\tangmax\n")
  #! format: on
  for (i, br) in enumerate(branchVec)
    fbus = br.fromBus
    tbus = br.toBus
    r = br.r_pu
    x = br.x_pu
    b = br.b_pu
    g = br.g_pu
    if abs(g) > 1e-6
      @info "Branch shunt conductance g is not directly represented by standard MATPOWER branch rows; export diagnostics should account for equivalent bus shunts" g
    end
    rateA = 0 # 0 for unlimited
    if !isnothing(br.sn_MVA)
      rateA = br.sn_MVA
    end
    rateB = 0 # 0 for unlimited
    rateC = 0 # 0 for unlimited

    kind = _matpower_branch_kind(net, i, br)
    ratio = kind == "T" ? br.ratio : 0.0
    angle = br.angle
    status = Int(br.status)
    angmin = -360 #br.angmin
    angmax = 360 #br.angmax

    type = br.comp.cName

    if br.status == 0 # out of service
      type = "(no service) " * type
    end

    cID = br.comp.cID
    #! format: off
    line = string(fbus, "\t", tbus, "\t", r, "\t", x, "\t", b, "\t", rateA, "\t", rateB, "\t", rateC, "\t", ratio, "\t", angle, "\t", status, "\t", angmin, "\t", angmax, "; %Branch: " * type * " (ID: " * cID * ")\n")
    #! format: on
    write(file, line)
  end # for

  write(file, "];\n")
end # writeBranchData

function _matpower_quote(s::AbstractString)
  return "'" * replace(String(s), "'" => "''") * "'"
end

_matpower_value(x::AbstractString) = _matpower_quote(x)
_matpower_value(x::Integer) = string(x)
_matpower_value(x::Real) = isfinite(Float64(x)) ? string(Float64(x)) : "NaN"

function writeSparlectraTransformerLossMetadata(net::Net, file, rows)
  isempty(rows) && return nothing
  write(file, "mpc.sparlectra = struct();\n")
  write(file, "mpc.sparlectra.format_version = 1;\n")
  write(file, "mpc.sparlectra.warning = ", _matpower_quote("This file contains Sparlectra-specific transformer loss metadata. Plain MATPOWER does not apply this extension. Results may deviate when run outside Sparlectra."), ";\n")
  write(file, "mpc.sparlectra.transformer_losses = {\n")
  for row in rows
    fields = String[]
    for name in propertynames(row)
      push!(fields, string(_matpower_quote(String(name)), ", ", _matpower_value(getproperty(row, name))))
    end
    write(file, "struct(", join(fields, ", "), ");\n")
  end
  write(file, "};\n")
  return nothing
end

function writeSparlectraMetadata(net::Net, file)
  write(file, "%% optional Sparlectra metadata (ignored by standard MATPOWER solvers)\n")
  write(file, "mpc.bus_name = {\n")
  for n in net.nodeVec
    write(file, _matpower_quote(n.comp.cName), ";\n")
  end
  write(file, "};\n")
  write(file, "mpc.branch_name = {\n")
  for (i, br) in enumerate(net.branchVec)
    meta = get(net.matpower_branch_metadata, i, nothing)
    name = meta !== nothing && hasproperty(meta, :orig_name) ? String(meta.orig_name) : br.comp.cName
    write(file, _matpower_quote(name), ";\n")
  end
  write(file, "};\n")
  write(file, "mpc.branch_kind = {\n")
  for (i, br) in enumerate(net.branchVec)
    kind = _matpower_branch_kind(net, i, br)
    write(file, _matpower_quote(kind), ";\n")
  end
  write(file, "};\n")
  if !isempty(net.for001Contingencies)
    write(file, "mpc.for001_contingencies = {\n")
    for contingency in net.for001Contingencies
      write(file, _matpower_quote(contingency), ";\n")
    end
    write(file, "};\n")
  end
  writeSparlectraTransformerLossMetadata(net, file, _sparlectra_transformer_loss_rows(net))
end

"""
    writeMatpowerCasefile(net::Net, pathfilename::String)

Write Matpower case files.

# Arguments
- `net::Net`: Network object.
- `pathfilename::String`: Path and filename to write the Matpower case file.

# Example
```julia
net = Net(...)
writeMatpowerCasefile(net, "casefile.m")
```
"""
function writeMatpowerCasefile(net::Net, pathfilename::String)
  base, ext = splitext(pathfilename)

  case = basename(base)
  base = base * ".m"
  @info "convertion to Matpower CASE-Files, Testcase: ($case)"
  transformer_loss_rows = _sparlectra_transformer_loss_rows(net)
  NodeDict = Dict{Int,Node}()
  for n in net.nodeVec
    NodeDict[n.busIdx] = n
  end

  file = open(pathfilename, "w")
  writeHeader(net.baseMVA, file, case; has_transformer_loss_metadata = !isempty(transformer_loss_rows))
  hasPVBus, slackIdx, vgSlack = writeBusData(net, file)

  writeGeneratorData(net.baseMVA, NodeDict, net.prosumpsVec, file, hasPVBus, slackIdx, vgSlack)

  writeBranchData(net, file)
  writeSparlectraMetadata(net, file)
  #writeCostData(file)
  close(file)
end # writeMatpowerCasefile
