name: Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Sparlectra and Documenter packages
        run: |
          julia -e 'using Pkg; Pkg.add(["Sparlectra", "Documenter"])'

      - name: Run make.jl script
        run: julia docs/make.jl

      - name: Copy build content to _site directory
        run: |
          mkdir -p _site/
          cp -r docs/build/* ./_site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3


      #- name: Upload _site directory as artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: site
      #    path: ./_site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      #- name: Download _site artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: site
      #    path: _site/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
