function mpc = sp_case9
% SP_CASE9  Nine-bus system in the shape of the classic three-machine test
% system: three generator buses behind step-up transformers (two of them on
% off-nominal taps), a 230 kV ring with three loads. Self-built, no external
% data, no external license. Generated by tools/gen_sp_cases.py.
%
% AC base case (Newton-Raphson, 5 iterations): Vmin 1.0061 pu at bus
% 6, Vmax 1.0400 pu, slack P 78.602 MW, highest branch
% loading 50.6 %.
%
% DC power-flow reference (independent implementation in the generator,
% MATPOWER conventions: B' from x and tap, Pfinj from the shift, slack bus 1).
% Used by test/test_dc_powerflow.jl as the DC anchor. Bus angles in degrees:
%   0.000000, 7.187830, 3.346158, -2.578310, -3.964097, -5.031808, 1.713218, -1.935803, 0.174836
% From-side active flows in MW, branch order as below:
%   (1,4) 75.0000, (2,7) 150.0000, (3,9) 90.0000, (4,5) 28.4548, (4,6) 46.5452, (5,7) -61.5452, (6,9) -53.4548, (7,8) 88.4548, (8,9) -36.5452
% Slack generation 75.0000 MW.

%% MATPOWER Case Format : Version 2
mpc.version = '2';

%%-----  Power Flow Data  -----%%
%% system MVA base
mpc.baseMVA = 100;

%% bus data
%	bus_i	type	Pd	Qd	Gs	Bs	area	Vm	Va	baseKV	zone	Vmax	Vmin
mpc.bus = [
	1	3	0.0	0.0	0.0	0.0	1	1.0	0.0	16.5	1	1.1	0.9;
	2	2	0.0	0.0	0.0	0.0	1	1.0	0.0	18.0	1	1.1	0.9;
	3	2	0.0	0.0	0.0	0.0	1	1.0	0.0	13.8	1	1.1	0.9;
	4	1	0.0	0.0	0.0	0.0	1	1.0	0.0	230.0	1	1.1	0.9;
	5	1	90.0	30.0	0.0	0.0	1	1.0	0.0	230.0	1	1.1	0.9;
	6	1	100.0	35.0	0.0	0.0	1	1.0	0.0	230.0	1	1.1	0.9;
	7	1	0.0	0.0	0.0	0.0	1	1.0	0.0	230.0	1	1.1	0.9;
	8	1	125.0	50.0	0.0	0.0	1	1.0	0.0	230.0	1	1.1	0.9;
	9	1	0.0	0.0	0.0	0.0	1	1.0	0.0	230.0	1	1.1	0.9;
];

%% generator data
%	bus	Pg	Qg	Qmax	Qmin	Vg	mBase	status	Pmax	Pmin
mpc.gen = [
	1	0.0	0.0	300.0	-300.0	1.04	100.0	1	250.0	10.0;
	2	150.0	0.0	120.0	-60.0	1.025	100.0	1	300.0	10.0;
	3	90.0	0.0	80.0	-40.0	1.025	100.0	1	270.0	10.0;
];

%% branch data
%	fbus	tbus	r	x	b	rateA	rateB	rateC	ratio	angle	status	angmin	angmax
mpc.branch = [
	1	4	0.0	0.06	0.0	250.0	250.0	250.0	1.0	0.0	1	-360.0	360.0;
	2	7	0.0	0.065	0.0	300.0	300.0	300.0	0.98	0.0	1	-360.0	360.0;
	3	9	0.0	0.06	0.0	300.0	300.0	300.0	1.025	0.0	1	-360.0	360.0;
	4	5	0.01	0.085	0.176	250.0	250.0	250.0	0.0	0.0	1	-360.0	360.0;
	4	6	0.017	0.092	0.158	250.0	250.0	250.0	0.0	0.0	1	-360.0	360.0;
	5	7	0.032	0.161	0.306	250.0	250.0	250.0	0.0	0.0	1	-360.0	360.0;
	6	9	0.039	0.17	0.358	150.0	150.0	150.0	0.0	0.0	1	-360.0	360.0;
	7	8	0.0085	0.072	0.149	250.0	250.0	250.0	0.0	0.0	1	-360.0	360.0;
	8	9	0.0119	0.1008	0.209	150.0	150.0	150.0	0.0	0.0	1	-360.0	360.0;
];

%% bus names (imported with matpower_import.apply_bus_names)
mpc.bus_name = {
	'Kraftwerk_Nord_16p5';
	'Kraftwerk_Ost_18p0';
	'Kraftwerk_Sued_13p8';
	'Ringpunkt_Nord_230';
	'Stadtwerk_West_230';
	'Industriepark_230';
	'Ringpunkt_Ost_230';
	'Umspannwerk_Mitte_230';
	'Ringpunkt_Sued_230';
};